### PR TITLE
Create BotClean Stochastic

### PR DESCRIPTION
**Pull request by Sakshi2002-Sinha**
Adding code for  BotClean Stochastic in C++.

### CODE REVIEW

**Comment by anomekumar08** [comment]
Sakshi! Move it to Python folder and delete it from main home page.

**Comment by Sakshi2002-Sinha** [comment]
> Sakshi! Move it to Python folder and delete it from main home page.

okay

**Comment by anomekumar08** [comment]
Oops! Sorry...Yes You have to move it to C++ folder

**Comment by anomekumar08** [comment]
Move it to C++ folder..and create pr with single commit...Sorry for inconvineance caused to you... @Sakshi2002-Sinha

**Pull request merged**
