### PR TITLE
Added 3Sum - Leetcode 

### PR DESCRIPTION
**Pull request by SubratYeeshu**
Please add under hacktoberfest2022

### CODE REVIEW

**Comment by anomekumar08** [comment]
Create a readme file and add some explanation of your program.

**Comment by SubratYeeshu** [comment]
Explanation added please merge under hacktoberfest2022

**Comment by SubratYeeshu** [comment]
@anomekumar08

**Comment by anomekumar08** [comment]
Okk..good @SubratYeeshu

**Pull request merged**
